### ISSUE TITLE
Cant add new tags by using + icon

### ISSUE THREAD

**Issue by Taxanas** [praegus/toolchain-fitnesse-plugin#10]
When adding new tag (by + icon) on page, which **doesn't currently have tag**, i get error:
`bootstrap-plus.js:859 Uncaught TypeError: Cannot read property 'length' of undefined`
Im using version 2.0.2, which is currently included in newest hsac fixtures (https://github.com/fhoeben/hsac-fitnesse-fixtures/releases/tag/4.14.0)

Error points to:
`// Check if tag already exist and if it has no special characters
    if (data[0].tags.length > 0 && data[0].tags.includes(lowerCaseTags) === true) {`

**Comment by tcnh** [comment]
This is fixed in version 2.0.3: https://github.com/praegus/toolchain-fitnesse-plugin/releases/tag/toolchain-fitnesse-plugin-2.0.3 (using bootstrap-plus 2.0.8)

next hsac-fitnesse-fixtures release contains 2.0.3, as the PR with the update was already merged

**Comment by Taxanas** [comment]
@tcnh , thank you for superfast response! 🥇
