### ISSUE TITLE
How to use conditional script/scenario

### ISSUE THREAD

**Issue by zhongwei1981** [praegus/toolchain-fitnesse-plugin#11]
I am trying to use your conditional script/scenario, but I failed to call them. Can you show me the details of the example. I do not know how to write the **boolean expression**.

Looking forward to your reply. Thanks.

| conditional script         |
| boolean expression         |
| normal script instructions |

| conditional scenario|do |stuff| if some variable equals abc |
| someVar == 'abc'                                            |
| script steps                                                |

**Comment by zhongwei1981** [comment]
The problem is that "ScriptEngine engine" is null, I do not know how to init it by "JavaScript".

private ScriptEngine engine;

  public SlimExpressionEvaluator() {
    this("JavaScript");
  }

**Comment by tcnh** [comment]
It uses Nashorn, which was deprecated from Java 11. Are you using a very recent JRE that might have it removed?

making it use graalVM is on my todo list, but I haven't found time to do so yet. (GraalVM is not as free-format as Nashorn allowed)

**Comment by zhongwei1981** [comment]
Used apache.commons.jexl3 to calculate Expression than javax.script.ScriptEngine, and it's OK for me.

**Comment by tcnh** [comment]
Closing this. let us know if you need any more help
