### ISSUE TITLE
Add possibility to disable 'create page' link, when included page is not found

### ISSUE THREAD

**Issue by joroelev** [praegus/toolchain-fitnesse-plugin#13]
In FitNesse a failed include currently results in a question mark being shown, that links to the 'create page' functionality.

![image](https://user-images.githubusercontent.com/5476742/81275710-5706c180-9052-11ea-96a2-6deb8afa397f.png)

In some contexts however, it is fine the included page is not found. E.g. when the page is only run after being symlinked into a location the has the included page available. 

Feature request: create a possibility to include a page in such a way that the 'create page' link is not shown when the page is not found. E.g. by creating something like !includeIfAvailable.

**Comment by tcnh** [comment]
2.0.8 contains !includeIfAvailable symbol, that works identical to !include, but shows only an informative message and no exception/create page link when the included page doesn't exist
